name: Deploy to Ubuntu Server with SSH Key

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Copy files to server using SSH
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ minsu@180.80.36.198:/home/minsu/portfoliogit